[phases.setup]
nixPkgs = ["nodejs", "postgresql"]

[phases.install]
cmds = ["npm ci --legacy-peer-deps"]

[phases.build]
cmds = [
  "npm install --legacy-peer-deps",
  "npx prisma generate",
  "npx prisma migrate deploy",
  "SKIP_ENV_VALIDATION=1 npm run build"
]

[start]
cmd = "npm run start"