import Header from "@/components/Header";
import {
  ColorSchemeScript,
  MantineColorsTuple,
  MantineProvider,
  createTheme,
} from "@mantine/core";
import "@mantine/core/styles.css";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import "./globals.css";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const primaryColor: MantineColorsTuple = [
  "#ebf9ff",
  "#d6f0fb",
  "#a8e1f8",
  "#79d1f7",
  "#5ac4f5",
  "#4bbbf5",
  "#41b8f6",
  "#35a1dc",
  "#278fc5",
  "#007cad",
];
const secondaryColor: MantineColorsTuple = [
  "#fcf9e9",
  "#f6f0d9",
  "#ebe0b2",
  "#dfce88",
  "#d6c064",
  "#d0b64d",
  "#cdb240",
  "#b59c31",
  "#a18a28",
  "#8b771b",
];
const theme = createTheme({
  fontFamily: "Open Sans, sans-serif",
  colors: {
    primary: primaryColor,
    secondary: secondaryColor,
  },
  primaryColor: "primary",
  cursorType: "pointer",
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="tr" suppressHydrationWarning>
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <SessionProvider>
          <MantineProvider forceColorScheme="light" theme={theme}>
            <Header />
            <main>{children}</main>
          </MantineProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
